dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
script:
  - ./mvnw clean install

notifications:
  email: cheresioana@gmail.com
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS lab4;'